<?php

/**
 * @file
 * This module exposes the Message Broker object library to Drupal.
 */

/**
 * Implements hook_libraries_info().
 */
function message_broker_producer_libraries_info() {

  $libraries['messagebroker-phplib'] = array(
    'name' => 'Message Broker PHP Library',
    'vendor url' => 'http://www.dosomething.org/message-broker-phplib',
    'download url' => 'https://github.com/DoSomething/message-broker-phplib',
    'version' => '1.0',
    'files' => array(
      'php' => array('MessageBroker.php'),
    ),
  );

  return $libraries;
}

/*
 * Implements hook_theme()
 */
function message_broker_producer_theme($existing, $type, $theme, $path) {
  return array(
    'message_broker_producer_status' => array(
      'variables' => array('status' => array()),
      'template' => 'templates/message-broker-producer-status',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function message_broker_producer_menu() {

   $items['admin/config/services/message-broker-producer'] = array(
    'title' => 'Message Broker',
    'description' => 'Message Broker resources - RabbitMQ status and settings.',
    'page callback' => 'message_broker_producer_status',
    'access arguments' => array('administer message_broker_producer'),
    'file' => 'message_broker_producer.admin.inc',
  );
  $items['admin/config/services/message-broker-producer/status'] = array(
    'title' => 'RabbitMQ Status',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10
  );
  $items['admin/config/services/message-broker-producer/mq-settings'] = array(
    'title' => 'RabbitMQ Settings',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('message_broker_producer_config_form'),
    'access arguments' => array('administer message_broker_producer'),
    'file' => 'message_broker_producer.admin.inc',
  );

  // Testing - remove for release
  $items['admin/config/services/message-broker-producer-test'] = array(
    'title' => 'Message Broker TEST',
    'description' => 'Message Broker Producer TEST',
    'page callback' => 'message_broker_producer_test',
    'access arguments' => array('administer message_broker_producer'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function message_broker_producer_permission() {
  return array(
    'administer message_broker_producer' =>  array(
      'title' => t('Administer Message Broker Producer'),
      'description' => t('Manage Message Broker Producer settings.'),
    )
  );
}

/**
 * Makes request to Message Broker PHP Library and RabbitMQ.
 *
 * @param $method
 *   The api method to request.
 *   @see For list of available methods - https://github.com/DoSomething/mobilecommons-php/blob/master/lib/MobileCommons/MobileCommons.php
 * @param $params
 *   An option associative array of parameters.
 *
 * @return
 *   A SimpleXML response object.
 */
function message_broker_producer_request($method = '', $param = array()) {

  $library = libraries_load('messagebroker-phplib');
  if (!empty($library['loaded'])) {
    if (!empty($method)) {

$bla = TRUE;
if ($bla) {
  $bla = TRUE;
}

      // Connect to RabbitMQ
      $credentials = array(
        'host' => variable_get('message_broker_producer_rabbitmq_host', ''),
        'port' => variable_get('message_broker_producer_rabbitmq_port', ''),
        'username' => variable_get('message_broker_producer_rabbitmq_username', ''),
        'password' => variable_get('message_broker_producer_rabbitmq_password', ''),
      );
      $MessageBroker = new MessageBroker($credentials);

      // Add 'activity_timestamp' and 'application_id' to $param for
      // produceTransactional method call
      $param['activity_timestamp'] = time();
      $application_id + variable_get('message_broker_producer_application_id', NULL);
      if (!empty($application_id)) {
        $param['application_id'] = $application_id;
      }
      else {
        drupal_set_message('The application ID has not been set.', 'error');
        return;
      }

      $param = json_encode($param);
      return $MessageBroker->$method($param);

    }
    else {
      drupal_set_message('The intended method for message_broker_producer_request() must be defined.', 'error');
      return;
    }
  }
  else {
    drupal_set_message('Failed to load messagebroker-phplib library.', 'error');
    return;
  }
}

/**
 * Loads StatHat library.
 *
 * @return
 *   TRUE if library is successfully loaded, FALSE if not.
 */
function message_broker_producer_test() {
  $payload = array(
    'activity' => 'campaign-signup',
    'event_id' => 8012345,
    'email' => 'dlee+messagebroker-test@dosomething.org',
  );
  message_broker_producer_request('produceTransactional', $payload);
}



